- hosts: www
  sudo: true
  serial: 1
  gather_facts: false
  user: fedora
  vars_files:
    - private/discourse.yml
  pre_tasks:
    - name: Mount pgsql volume
      action: mount src=/dev/xvdf1 name=/var/lib/pgsql fstype=ext4 opts=noatime state=present
  roles:
    - role: managed-host
      sysadmins:
        - name: tdfischer
          key: "{{ lookup('file', 'sysadmin-keys/tdfischer.pub') }}"
        - name: phuzion
          key: "{{ lookup('file', 'sysadmin-keys/phuzion.pub') }}"
        - name: gsvolt
          key: "{{ lookup('file', 'sysadmin-keys/gsvolt.pub') }}"
      extra_packages:
        - python-psycopg2

    - role: pgsql

    - role: discourse

    - role: uwsgi-server

    - role: nginx-uwsgi
      name: hackron.org
      nginx_append:
        - templates/hackron-nginx.conf
