- hosts: www
  serial: 1
  sudo: true
  gather_facts: false
  user: root
  vars_files:
    - private/discourse.yml
  tasks:
    - name: Install sidekiq-worker.service systemd unit for discourse
      action: template src=templates/discourse-sidekiq-worker.service dest=/etc/systemd/system/discourse-sidekiq-worker.service
      tags:
        - reconfigure
    - name: Activate sidekiq-worker.service
      action: service name=sidekiq-worker.service state=started
      tags:
        - services
  pre_tasks:
    - name: Mount pgsql volume
      action: mount src=/dev/xvdf1 name=/var/lib/pgsql fstype=ext4 opts=defaults,noatime state=present
    - name: Mount discourse volume
      action: mount src=/dev/xvdg1 name=/var/lib/discourse fstype=ext4 opts=defaults,noatime state=present
  roles:
    - role: managed-host
      sysadmins:
        - name: tdfischer
          key: "{{ lookup('file', 'sysadmin-keys/tdfischer.pub') }}"
        - name: phuzion
          key: "{{ lookup('file', 'sysadmin-keys/phuzion.pub') }}"
        - name: gsvolt
          key: "{{ lookup('file', 'sysadmin-keys/gsvolt.pub') }}"
      extra_packages:
        - python-psycopg2

    - role: pgsql

    - role: rails-app
      name: discourse
      git: https://github.com/discourse/discourse.git
      vcs_version: master
      uwsgi_mount: "/"
      uwsgi_domain: "discuss.hackron.org"
      uwsgi_config:
        src: templates/discourse.conf
        dest: "{{uwsgi_app_path}}/config/discourse.conf"

    - role: uwsgi-server

    - role: nginx-server
      name: hackron.org
      nginx_append:
        - templates/hackron-nginx.conf

    - role: nginx-uwsgi
      name: discuss.hackron.org
      nginx_append:
        - templates/hackron-discourse.conf
