- name: create discourse user
  user: name=discourse
        home=/var/lib/discourse
        createhome=yes
        shell=/sbin/nologin
        groups=wheel
        uid=30001

- name: make sure home dir is executable for non-discourse user
  file:
    state: directory
    mode: 0711
    path: /var/lib/discourse

- name: install requisit packages
  yum: state=installed name={{item}}
  with_items:
  - redis
  - ruby
  - rubygem-bundler
  - openssl-devel
  - ImageMagick
  - ruby-devel
  - make
  - rubygems-devel
  - gcc-c++
  - gcc
  - postgresql-devel
  - rubygem-rake
  - tk-devel
  - systemtap-sdt-devel
  - rubygem-minitest
  - readline-devel
  - ncurses-devel
  - libyaml-devel
  - libffi-devel
  - libdb-devel
  - gdbm-devel
  - autoconf

- name: install gems
  gem: state=present user_install=no name={{item}}
  with_items:
  - bluepill

- name: enable redis
  service: name=redis state=running enabled=yes

- name: set up database
  postgresql_db: name=discourse

- name: create pgsql role
  postgresql_user: db=discourse
                   priv=ALL
                   user=discourse
                   password={{discourse_postgresql_password}}
                   role_attr_flags=CREATEDB,NOSUPERUSER
                   login_user=postgres

- name: Load extensions
  shell: "/bin/psql -d discourse -c \"CREATE EXTENSION IF NOT EXISTS {{item}}\""
  sudo_user: postgres
  with_items:
    - pg_trgm
    - hstore

- name: clone down Discourse repository
  git: repo=https://github.com/discourse/discourse.git
       dest=/var/lib/discourse/app/
       version={{discourse_version}}
       update=yes

- name: chown to discourse user
  file: recurse=yes path=/var/lib/discourse/ owner=discourse group=discourse

- name: bundle
  shell: chdir=/var/lib/discourse/app/ bundle install --deployment --without test
  sudo_user: discourse

- name: install configuration files
  template: src={{item}} dest=/var/lib/discourse/app/config/{{item}} owner=discourse group=discourse
  with_items:
    - discourse.conf
    - redis.yml
    - discourse.pill

- name: install production environment config
  template: src=production.rb dest=/var/lib/discourse/app/config/environments/production.rb owner=discourse group=discourse

- name: Migrate database
  shell: >
    chdir=/var/lib/discourse/app/
    bin/rake db:migrate RAILS_ENV=production 
  sudo_user: discourse

- name: precompile assets
  shell: >
    chdir=/var/lib/discourse/app
    bin/rake assets:precompile RAILS_ENV=production

- name: load the pill
  shell: >
    chdir=/var/lib/discourse
    creates=/var/run/bluepill/socks/discourse.sock
    /usr/local/bin/bluepill --no-privileged load app/config/discourse.pill
  sudo_user: discourse

- name: start the pill
  shell: >
    chdir=/var/lib/discourse
    creates=/var/run/bluepill/pids/discourse.pid
    /usr/local/bin/bluepill --no-privileged start app/config/discourse.pill
  sudo_user: discourse

- name: Ensure nginx directory exists
  file: dest=/etc/nginx/conf.d/ state=directory

- name: install nginx conf
  notify: reload nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/conf.d/discourse.conf

